### ISSUE TITLE
Lines disappear as scale goes up - a 1 day plot show X, a 7 day plot doesn't.

### ISSUE THREAD

**Issue by pjmaker** [amcphail/plot#12]
Vivian, 

A long while ago we had a chat about the loss of data as scale grows. On my current plots if
I show 1 days data I can see the signal but once I scale it up it disappears. I had a look thru the
plot options but nothing leapt out at me. Its that fix still in there.

Ta

**Comment by amcphail** [comment]
Hi Phil,

If I recall correctly I added the function `sampleData` to flag whether
this should occur.

type SampleData = Bool
<http://hackage.haskell.org/package/base-4.7.0.1/docs/Data-Bool.html#t:Bool>
Source
<http://hackage.haskell.org/package/plot-0.2.3.4/docs/src/Graphics-Rendering-Plot-Types.html#SampleData>
sampleData :: SampleData
<http://hackage.haskell.org/package/plot-0.2.3.4/docs/Graphics-Rendering-Plot-Figure.html#t:SampleData>
-> Plot
<http://hackage.haskell.org/package/plot-0.2.3.4/docs/Graphics-Rendering-Plot-Figure.html#t:Plot>
()

Try putting `sampleData False` in your plot definition.

Unfortunately I just installed ghc 7.10.1 and the plot dependencies don't
compile yet (glib,gio,gtk).  So I don't have a working `plot` package.

Cheers,

VIvian

**Comment by pjmaker** [comment]
Thanks,

Worked perfectly, sorry for not keeping the orginal source.




On Mon, Apr 6, 2015 at 8:49 AM, Vivian McPhail <notifications@github.com>
wrote:

> Hi Phil,
>
> If I recall correctly I added the function `sampleData` to flag whether
> this should occur.
>
> type SampleData = Bool
> <
> http://hackage.haskell.org/package/base-4.7.0.1/docs/Data-Bool.html#t:Bool
> >
> Source
> <
> http://hackage.haskell.org/package/plot-0.2.3.4/docs/src/Graphics-Rendering-Plot-Types.html#SampleData
> >
> sampleData :: SampleData
> <
> http://hackage.haskell.org/package/plot-0.2.3.4/docs/Graphics-Rendering-Plot-Figure.html#t:SampleData
> >
> -> Plot
> <
> http://hackage.haskell.org/package/plot-0.2.3.4/docs/Graphics-Rendering-Plot-Figure.html#t:Plot
> >
> ()
>
> Try putting `sampleData False` in your plot definition.
>
> Unfortunately I just installed ghc 7.10.1 and the plot dependencies don't
> compile yet (glib,gio,gtk). So I don't have a working `plot` package.
>
> Cheers,
>
> VIvian
>
>
> On 6 April 2015 at 11:00, Phil Maker <notifications@github.com> wrote:
>
> > Vivian,
> >
> > A long while ago we had a chat about the loss of data as scale grows. On
> > my current plots if
> > I show 1 days data I can see the signal but once I scale it up it
> > disappears. I had a look thru the
> > plot options but nothing leapt out at me. Its that fix still in there.
> >
> > Ta
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/amcphail/plot/issues/12>.
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/amcphail/plot/issues/12#issuecomment-89868662>.
>



-- 
Phil Maker <philip.maker@gmail.com>  -- email to me, 24h response time
work: <phillip.maker@powerwater.com.au> -- email for work
+61 (0)415 629 100 (AU mobile) -- mobile in australia
+61 8 89 854 939  (AU direct) -- home phone
philip.maker (skype)

*"*We must be very careful when we give advice to younger people:
sometimes they follow it!" -- EWD

see rgd, ewd, bwk, ast, ken, dennis, rms, kirk, ag, nh, gb, lp, sjw,
[a-z][a-z][a-z]
