### ISSUE TITLE
Deprecated Functions

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [amcphail/plot#18]
--  While building package pango-0.13.6.0 using:
      /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 configure --with-ghc=/Users/williamrusnack/.stack/programs/x86_64-osx/ghc-8.6.4/bin/ghc --with-ghc-pkg=/Users/williamrusnack/.stack/programs/x86_64-osx/ghc-8.6.4/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/williamrusnack/.stack/snapshots/x86_64-osx/lts-13.13/8.6.4/pkgdb --package-db=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/pkgdb --libdir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/lib --bindir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/bin --datadir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/share --libexecdir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/libexec --sysconfdir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/etc --docdir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/doc/pango-0.13.6.0 --htmldir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/doc/pango-0.13.6.0 --haddockdir=/Users/williamrusnack/Documents/haskell-plotting/.stack-work/install/x86_64-osx/lts-13.13/8.6.4/doc/pango-0.13.6.0 --dependency=Cabal=Cabal-2.4.1.0-9MZFDeNrcJI10bcroa6pq8 --dependency=array=array-0.5.3.0 --dependency=base=base-4.12.0.0 --dependency=cairo=cairo-0.13.6.0-CRppg1TTUyHLcUDcpeA2DP --dependency=containers=containers-0.6.0.1 --dependency=directory=directory-1.3.3.0 --dependency=filepath=filepath-1.4.2.1 --dependency=glib=glib-0.13.7.0-CouBN9URvtcKaGTE3xPXLR --dependency=gtk2hs-buildtools=gtk2hs-buildtools-0.13.5.0-37JVY9vzeBB8KXS75w1zDf --dependency=mtl=mtl-2.2.2 --dependency=pretty=pretty-1.1.3.6 --dependency=process=process-1.6.5.0 --dependency=text=text-1.2.3.1
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/williamrusnack/Documents/haskell-plotting/.stack-work/logs/pango-0.13.6.0.log

    [1 of 2] Compiling Main             ( /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/Setup.hs, /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/Main.o )

    /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/Setup.hs:45:3: warning: [-Wdeprecations]
        In the use of ‘rewriteFile’
        (imported from Distribution.Simple.Utils):
        Deprecated: "Use rewriteFileEx so that Verbosity is respected"
       |
    45 |   rewriteFile targetFile $ unlines
       |   ^^^^^^^^^^^

    /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/Setup.hs:51:18: warning: [-Wdeprecations]
        In the use of ‘autogenModulesDir’
        (imported from Distribution.Simple.BuildPaths):
        Deprecated: "If you can, use 'autogenComponentModulesDir' instead, but if you really wanted package-global generated modules, use 'autogenPackageModulesDir'.  In Cabal 2.0, we avoid using autogenerated files which apply to all components, because the information you often want in these files, e.g., dependency information, is best specified per component, so that reconfiguring a different component (e.g., enabling tests) doesn't force the entire to be rebuilt.  'autogenPackageModulesDir' still provides a place to put files you want to apply to the entire package, but most users of 'autogenModulesDir' should seriously consider 'autogenComponentModulesDir' if you really wanted the module to apply to one component."
       |
    51 |     targetDir  = autogenModulesDir lbi
       |                  ^^^^^^^^^^^^^^^^^

    /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/Setup.hs:55:3: warning: [-Wdeprecations]
        In the use of ‘die’ (imported from Distribution.Simple.Utils):
        Deprecated: "Messages thrown with die can't be controlled with Verbosity; use die' instead, or dieNoVerbosity if Verbosity truly is not available"
       |
    55 |   die $ "unexpected pango version number: " ++ display version
       |   ^^^
    [2 of 2] Compiling StackSetupShim   ( /Users/williamrusnack/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/StackSetupShim.o )
    Linking /private/var/folders/zj/p9mj9djj3c3b4vjw5yzq1ckr0000gn/T/stack21074/pango-0.13.6.0/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/setup/setup ...
    Configuring pango-0.13.6.0...
    setup: The pkg-config package 'pangocairo' version >=1.10 is required but it
    could not be found.

**Comment by amcphail** [comment]
These are problems with pango and pangocairo.  I suspect they use functions that are deprecated in the new version of ghc you are using.
