### ISSUE TITLE
Compiling plot package error

### ISSUE THREAD

**Issue by thermohyaena** [amcphail/plot#24]
The following error is showing with compiling plot
<command line>: addDLL: libgthread-2.0-0 or dependencies not loaded. (Win32 error 193)

Description in powershell:
> [15 of 25] Compiling Graphics.Rendering.Plot.Render.Plot.Data
plot                      > 
plot                      > lib\Graphics\Rendering\Plot\Render\Plot\Data.hs:136:15: warning: [-Woverlapping-patterns]      
plot                      >     Pattern match is redundant
plot                      >     In a case alternative: _ -> ...
plot                      >     |        
plot                      > 136 |        
       _                  -> error "renderData: DataSeries not handled"
plot                      >     |

**Comment by amcphail** [comment]
Hi,

The snippet you have included is merely a warning.  The shown error function is quoting the code.

On the matter of the thread scope compile fail, I have never attempted to build using Powershell as the Cairo/Pango packages use Linux dev libraries.

I now use the Debian package from the Windows Store.  Graphics packages are supported to be run from the Debian shell prompt.

Hope this helps.

Vivian

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: thermohyaena ***@***.***>
Sent: Thursday, March 28, 2024 11:59:07 AM
To: amcphail/plot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [amcphail/plot] compiling plot package error (Issue #24)


The following error is showing with compiling plot
: addDLL: libgthread-2.0-0 or dependencies not loaded. (Win32 error 193)

Description in powershell:

[15 of 25] Compiling Graphics.Rendering.Plot.Render.Plot.Data
plot >
plot > lib\Graphics\Rendering\Plot\Render\Plot\Data.hs:136:15: warning: [-Woverlapping-patterns]
plot > Pattern match is redundant
plot > In a case alternative: _ -> ...
plot > |
plot > 136 |
_ -> error "renderData: DataSeries not handled"
plot > |

**Comment by thermohyaena** [comment]
I have downloaded the dll, and it worked just fine, thanks for your reply anyway!
